world_description:
  has_ground: True
  models:
    - model_file: "bin.sdf"
      root_body_name: "bin_base"
      pose:
        xyz: [0.5, 0., 0.]
        rpy: [0., 0., 0.]

placeable_objects:
  - model_file: "ycb/sdf/003_cracker_box.sdf"
    occurance:
      min: 0
      max: 3
      rate: 0.25
  - model_file: "ycb/sdf/004_sugar_box.sdf"
    occurance:
      min: 0
      max: 3
      rate: 0.25
  - model_file: "ycb/sdf/005_tomato_soup_can.sdf"
    occurance:
      min: 0
      max: 3
      rate: 0.25
  